services:
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    image: ervincaravaliibarra/backend:latest
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    image: ervincaravaliibarra/frontend:latest
    ports:
      - "5174:5174"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
